"""Add file_path column to Drawing model

Revision ID: 66c1bafb5494
Revises: 
Create Date: 2024-10-21 04:21:20.946199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c1bafb5494'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=120), nullable=False))
        batch_op.alter_column('data',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawing', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
